### ISSUE TITLE
[v4] Failing upload due to internal CLI error

### ISSUE THREAD

**Issue by CasperWA** [codecov/codecov-action#1246]
It seems the codecov-action is failing to upload due to an internal error in the codecov CLI?

Or maybe I've missed something in the update to v4?

Also, the `token` input seems to not be picket up any longer by the action, I had to change that input to an environment variable instead to even reach this far in the codecov-action progress.

Running on `ubuntu-latest`.

```console
==> Running version v0.4.5
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit -C 859cde07ea6d425dd1b5698126c14a65e4dc7f3e
==> Uploader SHASUM verified (b66c69fb5a2969d81f9f11307f8954d314a3b66896fc117de6e8d4c132bc5b13  codecov)
info - 2024-02-01 09:08:00,021 -- ci service found: github-actions
warning - 2024-02-01 09:08:00,021 -- Config file codecov.yml not found, or is not a file. Ignoring config.
info - 2024-02-01 09:08:00,128 -- Process Commit creating complete
error - 2024-02-01 09:08:00,128 -- Commit creating failed: ["Repository not found"]
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-report'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-report -C 859cde07ea6d425dd1b5698126c14a65e4dc7f3e
info - 2024-02-01 09:08:00,8[34](https://github.com/SINTEF/entities-service/actions/runs/7738765602/job/21100258177?pr=81#step:6:35) -- ci service found: github-actions
warning - 2024-02-01 09:08:00,834 -- Config file codecov.yml not found, or is not a file. Ignoring config.
info - 2024-02-01 09:08:00,923 -- Process Report creating complete
error - 2024-02-01 09:08:00,923 -- Report creating failed: ["Repository not found"]
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov do-upload'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov do-upload -e OS,PYTHON -Z -F local -C 859cde07ea6d425dd1b5698126c14a65e4dc7f3e
info - 2024-02-01 09:08:01,625 -- ci service found: github-actions
warning - 2024-02-01 09:08:01,626 -- Config file codecov.yml not found, or is not a file. Ignoring config.
warning - 2024-02-01 09:08:01,633 -- xcrun is not installed or can't be found.
warning - 2024-02-01 09:08:01,6[37](https://github.com/SINTEF/entities-service/actions/runs/7738765602/job/21100258177?pr=81#step:6:38) -- No gcov data found.
info - 2024-02-01 09:08:01,6[38](https://github.com/SINTEF/entities-service/actions/runs/7738765602/job/21100258177?pr=81#step:6:39) -- Generating coverage.xml report in /home/runner/work/entities-service/entities-service
info - 2024-02-01 09:08:01,810 -- Wrote XML report to coverage.xml
info - 2024-02-01 09:08:01,823 -- Found 1 coverage files to upload
info - 2024-02-01 09:08:01,823 -- > /home/runner/work/entities-service/entities-service/coverage.xml
info - 2024-02-01 09:08:01,914 -- Process Upload complete
error - 2024-02-01 09:08:01,915 -- Upload failed: ["Repository not found"]
Traceback (most recent call last):
  File "codecov_cli/main.py", line 81, in <module>
  File "codecov_cli/main.py", line 77, in run
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1[43](https://github.com/SINTEF/entities-service/actions/runs/7738765602/job/21100258177?pr=81#step:6:44)4, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 33, in new_func
  File "codecov_cli/commands/upload.py", line 232, in do_upload
  File "codecov_cli/services/upload/__init__.py", line 126, in do_upload_logic
  File "codecov_cli/helpers/request.py", line 133, in log_warnings_and_errors_if_any
NameError: name 'exit' is not defined
[2128] Failed to execute script 'main' due to unhandled exception!
Error: Codecov: 
                      Failed to properly upload report: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

**Comment by CasperWA** [comment]
Figured this one out - the reason is indeed the missing secret allowed for Dependabot (see #1248)

Also, the `token` input works fine.

**Comment by VitaliySerov** [comment]
Hey, maybe it's a good idea to reopen it

I also stumbled on that and also forget about Dependabot secret, but I don't thing error should be so vague and should show some graceful error, something like 'Please check that your tokens are correct' instead of stacktrace of python code
