### ISSUE TITLE
Request failed after too many retries

### ISSUE THREAD

**Issue by xni06** [codecov/codecov-action#1510]
```
debug - 2024-07-15 13:43:04,454 -- Running preparation plugin: <class 'codecov_cli.plugins.pycoverage.Pycoverage'>
warning - 2024-07-15 13:43:04,455 -- coverage.py is not installed or can't be found.
debug - 2024-07-15 13:43:04,455 -- Collecting relevant files
info - 2024-07-15 13:43:04,496 -- Found 1 coverage files to report
info - 2024-07-15 13:43:04,496 -- > /home/runner/work/ags/ags/coverage/lcov.info
debug - 2024-07-15 13:43:04,525 -- Selected uploader to use: <class 'codecov_cli.services.upload.upload_sender.UploadSender'>
debug - 2024-07-15 13:43:04,527 -- Sending upload request to Codecov
warning - 2024-07-15 13:43:04,677 -- Response status code was 500. --- {"retry": 0}
warning - 2024-07-15 13:43:04,677 -- Request failed. Retrying --- {"retry": 0}
warning - 2024-07-15 13:43:05,305 -- Response status code was 500. --- {"retry": 1}
warning - 2024-07-15 13:43:05,306 -- Request failed. Retrying --- {"retry": 1}
warning - 2024-07-15 13:43:06,599 -- Response status code was 500. --- {"retry": 2}
warning - 2024-07-15 13:43:06,599 -- Request failed. Retrying --- {"retry": 2}
Traceback (most recent call last):
  File "codecov_cli/main.py", line 85, in <module>
  File "codecov_cli/main.py", line 81, in run
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 16[88](https://github.com/Apex-Networks/ags/actions/runs/9939611929/job/27457217710#step:8:89), in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 33, in new_func
  File "codecov_cli/commands/upload.py", line 257, in do_upload
  File "codecov_cli/services/upload/__init__.py", line 112, in do_upload_logic
  File "codecov_cli/services/upload/upload_sender.py", line 73, in send_upload_data
  File "codecov_cli/helpers/request.py", line 82, in wrapper
Exception: Request failed after too many retries
[4055] Failed to execute script 'main' due to unhandled exception!
Error: Codecov:
                        Failed to properly upload report: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1 
```

**Comment by marwan-alloreview** [comment]
I'm having the same issue

**Comment by hamzaaitbenyissa** [comment]
Same issue: 
```shell
Run codecov/codecov-action@v4
....

Running version v0.7.2
...

Exception: Request failed after too many retries
[1747] Failed to execute script 'main' due to unhandled exception!
Error: Codecov:
                        Failed to properly upload report: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1


```

**Comment by xni06** [comment]
Works now
