### ISSUE TITLE
Error running codecov v2: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by miparnisari** [codecov/codecov-action#642]
I didn't change anything on my part 🤔 

```
Run codecov/codecov-action@v2.1.0
  with:
    token: ***
    files: ./coverageunitdynamo.out,./coverageunitmemory.out
    verbose: true
    fail_ci_if_error: true
  env:
    GOROOT: /opt/hostedtoolcache/go/1.17.6/x64
==> linux OS detected
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1[3](https://github.com/auth0/sandcastle/runs/5045159315?check_suite_focus=true#step:7:3)61:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:118[4](https://github.com/auth0/sandcastle/runs/5045159315?check_suite_focus=true#step:7:4):12)
    at processTicksAndRejections (internal/process/task_queues.js:[8](https://github.com/auth0/sandcastle/runs/5045159315?check_suite_focus=true#step:7:8)0:21)
```

**Comment by juliotux** [comment]
Same here. May be a server problem.

```
Run codecov/codecov-action@v2
==> linux OS detected
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by mkinney** [comment]
Looks like I picked the wrong time trying to setup a new repo... (similar error)

```
Run codecov/codecov-action@v2
==> macos OS detected
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: uploader.codecov.io. is not in the cert's altnames: DNS:api.codecov.io
    at Object.checkServerIdentity (tls.js:279:[12](https://github.com/mkinney/pytest-qt-example/runs/5045375110?check_suite_focus=true#step:7:12))
    at TLSSocket.onConnectSecure (_tls_wrap.js:[13](https://github.com/mkinney/pytest-qt-example/runs/5045375110?check_suite_focus=true#step:7:13)31:27)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```

**Comment by Nothing4You** [comment]
neither [github](https://www.githubstatus.com/) nor [codecov](https://status.codecov.com) acknowledge any issues on their status pages yet :/

**Comment by Nothing4You** [comment]
may be fixed again?
just had a job pass

**Comment by mkinney** [comment]
Works now for me, too.
